name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3
      -  uses: docker/setup-buildx-action@v3

      - name: Start MongoDB container
        run: |
          docker compose -f docker-compose-test.yml up -d --wait
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Tear down MongoDB container
        if: always()
        run: docker compose -f docker-compose-test.yml down